export const INITIALACTION = "INITIALACTION";
export const SELECTED = "SELECTED";
export const MATRIXUPDATE = "MATRIXUPDATE";
export const MATRIXINITIALACTION = "MATRIXINITIALACTION";
export const MATRIXSELECTED = "MATRIXSELECTED";
export const SELECTEDDIAMENTIONALUPDATE = "SELECTEDDIAMENTIONALUPDATE";



